links = {
    "Andorra": "https://www.plonkit.net/andorra",
    "Argentina": "https://www.plonkit.net/argentina",
    "Australia": "https://www.plonkit.net/australia",
    "Bangladesh": "https://www.plonkit.net/bangladesh",
    "Belgium": "https://www.plonkit.net/belgium",
    "Bhutan": "https://www.plonkit.net/bhutan",
    "Botswana": "https://www.plonkit.net/botswana",
    "Brazil": "https://www.plonkit.net/brazil",
    "Bulgaria": "https://www.plonkit.net/bulgaria",
    "Cambodia": "https://www.plonkit.net/cambodia",
    "Canada": "https://www.plonkit.net/canada",
    "Chile": "https://www.plonkit.net/chile",
    "Colombia": "https://www.plonkit.net/colombia",
    "Croatia": "https://www.plonkit.net/croatia",
    "Czech Republic": "https://www.plonkit.net/czechia",
    "Denmark": "https://www.plonkit.net/denmark",
    "Estonia": "https://www.plonkit.net/estonia",
    "Finland": "https://www.plonkit.net/finland",
    "France": "https://www.plonkit.net/france",
    "Germany": "https://www.plonkit.net/germany",
    "Greece": "https://www.plonkit.net/greece",
    "Hong Kong": "https://www.plonkit.net/china",
    "Hungary": "https://www.plonkit.net/hungary",
    "Iceland": "https://www.plonkit.net/iceland",
    "Indonesia": "https://www.plonkit.net/indonesia",
    "Ireland": "https://www.plonkit.net/ireland",
    "Israel": "https://www.plonkit.net/israel-west-bank",
    "Italy": "https://www.plonkit.net/italy",
    "Japan": "https://www.plonkit.net/japan",
    "Korea": "https://www.plonkit.net/south-korea",
    "Latvia": "https://www.plonkit.net/latvia",
    "Lithuania": "https://www.plonkit.net/lithuania",
    "Malaysia": "https://www.plonkit.net/malaysia",
    "Mexico": "https://www.plonkit.net/mexico",
    "Netherlands": "https://www.plonkit.net/netherlands",
    "New Zealand": "https://www.plonkit.net/new-zealand",
    "Norway": "https://www.plonkit.net/norway",
    "Peru": "https://www.plonkit.net/peru",
    "Poland": "https://www.plonkit.net/poland",
    "Portugal": "https://www.plonkit.net/portugal",
    "Romania": "https://www.plonkit.net/romania",
    "Russian Federation": "https://www.plonkit.net/russia",
    "Singapore": "https://www.plonkit.net/singapore",
    "Slovakia": "https://www.plonkit.net/slovakia",
    "Slovenia": "https://www.plonkit.net/slovenia",
    "South Africa": "https://www.plonkit.net/south-africa",
    "Spain": "https://www.plonkit.net/spain",
    "Swaziland": "https://www.plonkit.net/eswatini",
    "Sweden": "https://www.plonkit.net/sweden",
    "Switzerland": "https://www.plonkit.net/switzerland",
    "Taiwan": "https://www.plonkit.net/taiwan",
    "Thailand": "https://www.plonkit.net/thailand",
    "Ukraine": "https://www.plonkit.net/ukraine",
    "United Arab Emirates": "https://www.plonkit.net/united-arab-emirates",
    "United Kingdom": "https://www.plonkit.net/united-kingdom",
    "United States": "https://www.plonkit.net/united-states",
}
